### ISSUE TITLE
show warning when package.json version is not valid

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/gscan#15]
If the theme package.json contains e.g. `1.0`, the validation fails with an error.
We would like to change this error into a warning if possible.

**Comment by ErisDS** [comment]
Reopening this issue, temporarily (I already have a fix) because this problem is not just true for the version.

The current rules in Ghost are that any package.json issues are warnings only. Including non-existence of the package.json, or badly-formed JSON, or even if we find that there is no name or version which we depend on.  There is no validation of any of the fields at present.

At the moment, with the introduction of gscan, we have changed this to still be a warning if the JSON file is not present, but if there are any errors with it other than the version being invalid, we get an error and the theme won't upload. 

We need to actually make all of the package.json errors be warning-level, rather than error level. 

This will make gscan operate the same as the existing behaviour in Ghost, and we can start work on improving this, making our own set of proper validations for the package.json file, for the next version of Ghost, and for gscan 1.0.0 :grin:
