### ISSUE TITLE
Outdated {{id}}

### ISSUE THREAD

**Issue by milkv** [TryGhost/gscan#179]
* Casper Version: 2.9.6
Consider fixing:
- recommendation The output of <code>{{id}}</code> changed in Ghost v1.0.0, you may need to use <code>{{comment_id}}</code> instead.
    Files: post.hbs

**Comment by kevinansfield** [comment]
Hey @milkv 👋 I've moved the issue from Casper to GScan as it's more of a problem with the messaging than a problem in casper.

The line in Casper that's producing the warning is this:

```handlebars
{{#get "posts" filter="tags:{{primary_tag.slug}}+id:-{{id}}" limit="3" as |related_posts|}}
```

In this case the use of `{{id}}` is expected as it's genuinely using the post ID rather than the comment_id.

**Comment by kevinansfield** [comment]
I don't think there's anything we can do about this particular case, the message is already at the lowest level (recommendation) which is a hint towards something you should look at and confirm rather than something that needs changing. As such I'm going to close the issue.

**Comment by adamkudrna** [comment]
Hey guys!  First of all, thank you for maintaining gscan. I run it on each build, before every deploy, and it helps me save my time.

I've been facing this very same issue since I implemented related posts in the way mentioned above:

```hbs
        {{#get "posts"
            include="authors,tags"
            filter="primary_tag:{{primary_tag.slug}}+id:-{{id}}"
            limit="3"
            as |recent|
        }}
```

… which I believe is absolutely correct (it works).

However, there is this yellow message left after every gscan run. I cannot do anything with it but to ignore it. I know it's just a recommendation, but it looks much like a — more serious — warning. I'm afraid this will lead to ignoring errors and warnings in console one day. In the end, it could make gscan useless just because of an obsolete rule.

![image](https://user-images.githubusercontent.com/5614085/78711328-14e54580-7917-11ea-8a72-d27519414837.png)

Do you think it would be possible eg. to fire this rule only for versions < 1 based on Ghost version in `package.json`?

```json
  "engines": {
    "ghost": ">=3.9.0",
    "ghost-api": "v3",
    "node": ">=12"
  },
```

Thank you! 🌻

**Comment by adriatic** [comment]
Joining @adamkudrna - same proposal for the same reason. Running into this warning, knowing next to nothing about ghost is a mild shock
