### ISSUE TITLE
Using ".page" class should not give an error

### ISSUE THREAD

**Issue by WaqasIbrahim** [TryGhost/gscan#93]
Hi, I see that `{{body_class}}` outputs `.page-template` for page context. But `{{post_class}}` outputs `.page` class on static pages and I am referencing this class in my CSS files so it should not give a warning/error.

https://github.com/TryGhost/gscan/blob/06bd8fd02f3a760b817d84474deebc0067d5136e/lib/spec.js#L279
https://themes.ghost.org/docs/post_class

**Comment by kirrg001** [comment]
Hey @WaqasIbrahim!

Yeah sounds correct, it should not detect the `.page` class when using the `{{post_class}}` helper. The good thing is that you can still activate your theme in production, because it's a none fatal error.

I think it's hard to differentiate this 🤔 . Maybe we could downgrade the rule to a warning and optimise the description. How does your CSS definition looks like for `.page`?

**Comment by pbzona** [comment]
I got this error when I had been using a static `.page` class as part of a BEM model in my CSS, in addition to the `{{post_class}}` helper. This was my fault for not reading the context docs closely enough, but I think it's also a common design pattern that can be confusing when it gives a deprecation error.

I agree it would be helpful to downgrade to a warning. But if it *does* detect `.page` when not using `{{post_class}}`, maybe it should use a different warning message that the `.page` class is reserved for the helper, not just that it has been deprecated. 

Thanks for all your great work by the way. I've been using Ghost for a couple years and this is the first time I've ever had an issue that took more than a couple minutes to figure out.

**Comment by WaqasIbrahim** [comment]
Hello @kirrg001 , Here is the SCSS for `.page` class:
```css
.page {
	.content {
		padding-top: $phi * 1rem;
		padding-bottom: $phi * 1rem;
	}
}
```
