### ISSUE TITLE
Permission Errors

### ISSUE THREAD

**Issue by frantzypants** [TryGhost/gscan#96]
Related to: https://github.com/TryGhost/Support/issues/515

We have had reports of a few users (so far I've seen this twice personally) having permission issues on their theme uploads, where they receive an error like this:

![](https://camo.githubusercontent.com/46dfbd187ca67486d53d9b6801aef2d8f005676f/68747470733a2f2f7075752e73682f7a4c395a6e2f636532633661386363622e706e67)

From @kirrg001 

I would say this is an improvement, rather than a bug. This can be added in gscan.
If we extract the zip, we have to ensure that we set a default file and folder permission. [The library](https://github.com/maxogden/extract-zip) we are using offers the option to configure default file and folder permission.

**Comment by realthargor** [comment]
It's probably not that easy since extract only uses these options if there are no information on permission in the zip file. See [here](https://github.com/maxogden/extract-zip/blob/4fe49d66b07abf95eaaf52400acb84c9aaa3cc55/index.js#L109) and [here](https://github.com/maxogden/extract-zip/blob/4fe49d66b07abf95eaaf52400acb84c9aaa3cc55/index.js#L128)

Also zip files with permissions that prevent gscan from checking their content should be reported as defect, since ghost probably won't be able to read the content either.

If you want to have a check for that, you would have to break the current pattern of checks, since all run in parallel and most will throw an exception.
It's possible to catch these exception(s) and generate an error based on a rule... but the user would end up with multiple error messages for the same problem.

I would advise to define one fatal rule for EACCES Exception, catch those probably [here](https://github.com/TryGhost/gscan/blob/f5e01c4f911b1f2c69847fd061cbf323d460de19/lib/index.js#L26) generate the error and end the programm.

**Comment by kirrg001** [comment]
@realthargor Thanks for initial investigation.

> It's probably not that easy since extract only uses these options if there are no information on permission in the zip file. See here and here

Any idea why? Is this on purpose or simply not implemented?

**Comment by realthargor** [comment]
Nope, but I just noticed it is also documented, so definitely intended.
Adding a feature to override permission on extracted files is probably unwanted, since that can easily accomplished by use fs.chmod afterwards.

**Comment by kirrg001** [comment]
> Adding a feature to override permission on extracted files is probably unwanted, since that can easily accomplished by use fs.chmod afterwards.

Can you please expand what your concern is? Thanks!

I think:

- nobody can execute `fs.chmod` from the code (except you modify your copy of Ghost+Gscan).
- the permissions we would like to set is: read and write by the owner, read by group and others (644)
- you can't use `chmod` if you are not the owner of the file (except you are root or you are part of the sudoers group).

Extracting themes with the same permissions is in my opinion important, otherwise you end up in a situation where your files have different permissions. The Ghost CLI could complain about permissions on `ghost start` and you have no clue why.

**Comment by realthargor** [comment]
`fs.chown` is probably not possible, but not needed since all files resulting from an unzip-operation are owned by the user of the processes executing the unzip.
Hence `fs.chmod` should always be possible.

So three options:
1. Detect and report error in gscan and ghost
2. Change permission in gscan and ghost
3. Enable extract-zip to enforce permission

An example of a zip file having this problem would be very helpful.

**Comment by kirrg001** [comment]
> Enable extract-zip to enforce permission

Is there an open issue in extract-zip?

> An example of a zip file having this problem would be very helpful.

You can simulate this case by adding a file to a zip which has poor permissions.

**Comment by gargol** [comment]
The only way I was able to reproduce a permission error was by removing all the permission from the file, see `author.hbs` below: 
```
➜ ll author.hbs index.hbs page.hbs 
---------- 1 gargol gargol 2286 May  1 17:12 author.hbs
-rw-r----- 1 gargol gargol 1069 May  1 17:12 index.hbs
-rw----r-- 1 gargol gargol 2089 May  1 17:12 page.hbs
```

When creating a .zip file `authors.hbs` by default file was skipped completely, and only was added when running with `sudo`. Would say this is a quite unrealistic situation to run into :thinking: 

Think if that's the case, think the improvement we could do is returning a more specific error from `gscan` [itself](https://github.com/TryGhost/gscan/blob/master/lib/index.js#L33) something like:
```
if (err.code === 'EACCES') {
    throw new errors.ValidationError({
        message: 'Failed to read zip file or it\'s contents',
        help: 'Your zip file contains files with invalid permissions. Please make sure all files have correct permissions',
        errorDetails: err.message, // contains file that is lacking any permissions
        context: zip.name
    });
}
```

@frantzypants it would be great if you could dig up a zip file that was causing the error, as it's hard to reason about the error otherwise. Did this issue happen any more at all? 

Also, the image linked in the issue description is gone now  :smile:

**Comment by gargol** [comment]
this issue was not reproducible and has been stale for a while. as it never came in a year time, can be reopened if something similar ever comes up.
